# Generated by Django 5.1.15 on 2025-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_submission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="student_name",
        ),
        migrations.AddField(
            model_name="submission",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
