# Generated by Django 5.1.15 on 2025-12-07 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_submission_student_name_submission_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="enrollment_code",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="TestEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="accounts.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("student", "test")},
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="student_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
