# Generated by Django 5.1.15 on 2025-12-07 00:01

from django.db import migrations
import secrets
import string


def generate_enrollment_codes(apps, schema_editor):
    """Generate enrollment codes for existing tests that don't have one"""
    Test = apps.get_model('accounts', 'Test')

    def create_unique_code(existing_codes):
        chars = string.ascii_uppercase + string.digits
        while True:
            code = ''.join(secrets.choice(chars) for _ in range(8))
            if code not in existing_codes:
                return code

    tests_without_codes = Test.objects.filter(enrollment_code__isnull=True)
    existing_codes = set(Test.objects.exclude(enrollment_code__isnull=True).values_list('enrollment_code', flat=True))

    for test in tests_without_codes:
        test.enrollment_code = create_unique_code(existing_codes)
        existing_codes.add(test.enrollment_code)
        test.save(update_fields=['enrollment_code'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_test_enrollment_code_testenrollment_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_enrollment_codes, migrations.RunPython.noop),
    ]
