"""
Find and remove duplicate/conflicting migration files
"""

import os
import sys

migrations_dir = os.path.join(os.path.dirname(__file__), 'smartgrader_app', 'accounts', 'migrations')

print("="*70)
print("MIGRATION FILE CLEANUP")
print("="*70)
print(f"\nSearching in: {migrations_dir}\n")

if not os.path.exists(migrations_dir):
    print(f"❌ Migrations directory not found!")
    sys.exit(1)

# List all migration files
migration_files = []
for filename in sorted(os.listdir(migrations_dir)):
    if filename.endswith('.py') and not filename.startswith('__'):
        filepath = os.path.join(migrations_dir, filename)
        migration_files.append((filename, filepath))

print("Found migration files:")
for i, (filename, filepath) in enumerate(migration_files, 1):
    size = os.path.getsize(filepath)
    print(f"  [{i}] {filename} ({size} bytes)")

# Look for problematic files
print("\n" + "="*70)
print("CHECKING FOR PROBLEMS:")
print("="*70)

# Check for multiple 0005 files
files_0005 = [f for f in migration_files if '0005' in f[0]]
if len(files_0005) > 1:
    print(f"\n⚠️  Found {len(files_0005)} different 0005 migration files:")
    for filename, filepath in files_0005:
        print(f"     - {filename}")

    print("\n  The correct file should be:")
    print("     0005_test_enrollment_code_testenrollment_and_more.py")

    print("\n  Files to DELETE:")
    for filename, filepath in files_0005:
        if filename != '0005_test_enrollment_code_testenrollment_and_more.py':
            print(f"     ❌ {filename}")
            print(f"        Path: {filepath}")

    print("\n💡 Delete the wrong files manually or run this script with --delete flag")

elif len(files_0005) == 1:
    print(f"✓ Only one 0005 migration file found: {files_0005[0][0]}")
else:
    print("⚠️  No 0005 migration files found!")

# Check for any files that might be auto-generated
print("\n" + "="*70)
print("LOOKING FOR AUTO-GENERATED MIGRATIONS:")
print("="*70)

known_migrations = {
    '0001_initial.py',
    '0002_test.py',
    '0003_submission.py',
    '0004_remove_submission_student_name_submission_first_name_and_more.py',
    '0005_test_enrollment_code_testenrollment_and_more.py',
    '0006_generate_enrollment_codes.py',
    '__init__.py',
}

unknown_files = [f for f in migration_files if f[0] not in known_migrations]

if unknown_files:
    print("\n⚠️  Found unexpected migration files:")
    for filename, filepath in unknown_files:
        print(f"     ❌ {filename}")
        print(f"        This file might be auto-generated by makemigrations")
        print(f"        Path: {filepath}")

    if '--delete' in sys.argv:
        print("\n  Deleting unexpected files...")
        for filename, filepath in unknown_files:
            os.remove(filepath)
            print(f"     ✓ Deleted: {filename}")
else:
    print("\n✓ All migration files are expected (no auto-generated files)")

print("\n" + "="*70)
print("\nTo delete unexpected files automatically, run:")
print("  python cleanup_migrations.py --delete")
print("="*70)
